import "@/app/globals.css";
import "leaflet/dist/leaflet.css";
import "leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.css";

import { Montserrat } from "next/font/google";

import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
// import { SocketProvider } from "@/components/providers/SocketProvider";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

const montserrat = Montserrat({
  subsets: ['latin'],

})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          {/* <SocketProvider> */}
            {children}
          {/* </SocketProvider> */}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
